# Use a lightweight Node version
FROM node:18.11.0-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

EXPOSE 5000

# Start the application
CMD ["npm", "start"]
